<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
    <AssemblyVersion>1.0.*</AssemblyVersion>
    <Deterministic>False</Deterministic>
    <BlazorWebAssemblyEnableLinking>false</BlazorWebAssemblyEnableLinking>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Blazored.Modal" Version="4.1.0" />
	  <PackageReference Include="AspNetCore.SassCompiler" Version="1.102.0" />
	  <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.10" />
	  <PackageReference Include="LiveChartsCore.SkiaSharpView.Blazor" Version="2.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.10" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
	  <ServiceWorker Include="wwwroot\service-worker.js" PublishedContent="wwwroot\service-worker.published.js" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SpotifyService\Caerostris.Services.Spotify.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\Text.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Text.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Text.hu.resx">
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Text.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Text.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
